-- Seed: all Tunisian public higher education institutions.
-- Source: Portail National des Donnees Ouvertes (data.gov.tn), dataset
-- "etablissements publics denseignement superieur" (206 institutions).
-- Display format: "<ACRONYM> <city>[ (governorate)] -- <official French name>"
-- so admins/subscribers can search by common acronym (ISET, FSEG, ISG...),
-- by city, or by the full official name, all in the existing faculties.name column.
-- Safe to re-run: existing rows are left untouched (name is unique).

insert into public.faculties (name) values
  ('ENAU Tunis — Ecole Nationale d''Architecture et d''Urbanisme de Tunis'),
  ('ENETCOM Sfax — Ecole Nationale d''Electronique et des Télécommunications de Sfax'),
  ('ENI Bizerte — Ecole Nationale d''Ingénieurs de Bizerte'),
  ('ENI Carthage (Ariana) — Ecole Nationale d''Ingénieurs de Carthage'),
  ('ENI Gabès — Ecole Nationale d''Ingénieurs de Gabès'),
  ('ENI Gafsa — Ecole Nationale d''Ingénieurs de Gafsa'),
  ('ENI Monastir — Ecole Nationale d''Ingénieurs de Monastir'),
  ('ENI Sfax — Ecole Nationale d''Ingénieurs de Sfax'),
  ('ENI Sousse — Ecole Nationale d’Ingénieurs de Sousse'),
  ('ENIT (Tunis) — Ecole Nationale d''Ingénieurs de Tunis'),
  ('ENMV Sidi Thabet (Ariana) — Ecole Nationale de Médecine Vétérinaire de Sidi Thabet'),
  ('ENS (Tunis) — Ecole Normale Supérieure'),
  ('ENSI (La Mannouba) — Ecole Nationale des Sciences de l''Informatique'),
  ('ENSI Tunis — Ecole Nationale Supérieure d''Ingénieurs de Tunis'),
  ('ENSTA Borj Cédria (Nabeul) — Ecole Nationale des Sciences et Technologies Avancées de Borj Cédria'),
  ('EPT (Tunis) — Ecole Polytechnique de Tunisie'),
  ('ESA Kef (Le Kef) — Ecole Supérieure d''Agriculture du Kef'),
  ('ESA Mateur (Bizerte) — Ecole Supérieure d''Agriculture de Mateur'),
  ('ESA Mograne (Zaghouan) — Ecole Supérieure d''Agriculture de Mograne'),
  ('ESAC Gammarth (Tunis) — Ecole Supérieure de l''Audiovisuel et du Cinéma de Gammarth'),
  ('ESC Sfax — Ecole Supérieure de Commerce de Sfax'),
  ('ESC Tunis (La Mannouba) — Ecole Supérieure de Commerce de Tunis'),
  ('ESEN (La Mannouba) — Ecole Supérieure d''Economie Numérique'),
  ('ESI Medjez El Bab (Béja) — Ecole Supérieure des Ingénieurs de Medjez El Bab'),
  ('ESIA Tunis — Ecole Supérieure des Industries Alimentaires de Tunis'),
  ('ESSAI (Ariana) — Ecole Supérieure des Statistiques et d''Analyse de l''Information'),
  ('ESSEC Tunis — Ecole Supérieure des Sciences Economiques et Commerciales de Tunis'),
  ('ESST Design (La Mannouba) — Ecole Supérieure des Sciences et Technologies du Design'),
  ('ESST Hammam Sousse (Sousse) — Ecole Supérieure des Sciences et des Technologies de Hammam Sousse'),
  ('ESSTS Monastir — Ecole Supérieure des Sciences et Techniques de la Santé de Monastir'),
  ('ESSTS Sfax — Ecole Supérieure des Sciences et Techniques de la Santé de Sfax'),
  ('ESSTS Sousse — Ecole Supérieure des Sciences et Techniques de la Santé de Sousse'),
  ('ESSTS Tunis — Ecole Supérieure des Sciences et Techniques de la Santé de Tunis'),
  ('FD Sfax — Faculté de Droit de Sfax'),
  ('FDSP Sousse — Faculté de Droit et des Sciences Politiques de Sousse'),
  ('FDSP Tunis — Faculté de Droit et des Sciences Politiques de Tunis'),
  ('FLAH Manouba (La Mannouba) — Faculté des Lettres, des Arts et des Humanités de la Manouba'),
  ('FLSH Kairouan — Faculté des Lettres et des Sciences Humaines de Kairouan'),
  ('FLSH Sfax — Faculté des Lettres et Sciences Humaines de Sfax'),
  ('FLSH Sousse — Faculté des Lettres et des Sciences Humaines de Sousse'),
  ('FM Monastir — Faculté de Médecine de Monastir'),
  ('FM Sfax — Faculté de Médecine de Sfax'),
  ('FM Sousse — Faculté de Médecine de Sousse'),
  ('FM Tunis — Faculté de Médecine de Tunis'),
  ('FMD Monastir — Faculté de Médecine Dentaire de Monastir'),
  ('FP Monastir — Faculté de Pharmacie de Monastir'),
  ('FS Bizerte — Faculté des Sciences de Bizerte'),
  ('FS Gabès — Faculté des Sciences de Gabès'),
  ('FS Gafsa — Faculté des Sciences de Gafsa'),
  ('FS Monastir — Faculté des Sciences de Monastir'),
  ('FS Sfax — Faculté des Sciences de Sfax'),
  ('FSEG Mahdia — Faculté des Sciences Economiques et de Gestion de Mahdia'),
  ('FSEG Nabeul — Faculté des Sciences Economiques et de Gestion de Nabeul'),
  ('FSEG Sfax — Faculté des Sciences Economiques et de Gestion de Sfax'),
  ('FSEG Sousse — Faculté des Sciences Economiques et de Gestion de Sousse'),
  ('FSEG Tunis — Faculté des Sciences Economiques et de Gestion de Tunis'),
  ('FSHS Tunis — Faculté des Sciences Humaines et Sociales de Tunis'),
  ('FSJEG Jendouba — Faculté des Sciences Juridiques, Economiques et de Gestion de Jendouba'),
  ('FSJPS Tunis — Faculté des Sciences Juridiques, Politiques et Sociales de Tunis'),
  ('FST Sidi Bouzid — Faculté des Sciences et Techniques de Sidi Bouzid'),
  ('FST Tunis — Faculté des Sciences Mathématiques Physiques et Naturelles de Tunis'),
  ('IHEC Carthage (Tunis) — Institut des Hautes Etudes Commerciales de Carthage'),
  ('IHEC Sfax — Institut des Hautes Etudes Commerciales de Sfax'),
  ('IHEC Sousse — Institut des Hautes Etudes Commerciales de Sousse'),
  ('INAT (Tunis) — Institut National Agronomique de Tunisie'),
  ('INSAT Tunis — Institut National des Sciences Appliquées et de Technologie de Tunis'),
  ('INTES Tunis (Ariana) — Institut National du Travail et des Etudes Sociales de Tunis'),
  ('INTS Kef (Jendouba) — Institut National des Technologies et des Sciences du Kef'),
  ('IPEI Bizerte — Institut Préparatoire aux Etudes d''Ingénieurs de Bizerte'),
  ('IPEI Gafsa — Institut Préparatoire aux Etudes d''Ingénieurs de Gafsa'),
  ('IPEI Kairouan — Institut Préparatoire aux Etudes d''Ingénieurs de Kairouan'),
  ('IPEI Monastir — Institut Préparatoire aux Etudes d''Ingénieurs de Monastir'),
  ('IPEI Nabeul — Institut Préparatoire aux Etudes d''Ingénieurs de Nabeul'),
  ('IPEI Sfax — Institut Préparatoire aux Etudes d''Ingénieurs de Sfax'),
  ('IPEI Tunis — Institut Préparatoire aux Etudes d''Ingénieurs de Tunis'),
  ('IPEIEM (Tunis) — Institut Préparatoire aux Etudes d''Ingénieurs d''El Manar'),
  ('IPELSH Tunis — Institut Préparatoire aux Etudes Littéraires et des Sciences Humaines de Tunis'),
  ('IPEST (Tunis) — Institut Préparatoire aux Etudes Scientifiques et techniques'),
  ('IPSI (La Mannouba) — Institut de Presse et des Sciences de l''Information'),
  ('ISA Chott Mériem (Sousse) — Institut Supérieur Agronomique de Chott Mériem'),
  ('ISAA Sfax — Institut Supérieur d''Administration des Affaires de Sfax'),
  ('ISAD Tunis — Institut Supérieur d''Art Dramatique de Tunis'),
  ('ISAE Gafsa — Institut Supérieur d''Administration des Entreprises de Gafsa'),
  ('ISAJC Bir El Bey (Ben Arous) — Institut Supérieur de l''Animation pour la Jeunesse et la Culture de Bir El Bey'),
  ('ISAM Gabès — Institut Supérieur des Arts et Métiers de Gabès'),
  ('ISAM Gafsa — Institut Supérieur des Arts et Métiers de Gafsa'),
  ('ISAM Kairouan — Institut Supérieur des Arts et Métiers de Kairouan'),
  ('ISAM Kasserine — Institut Supérieur des Arts et Métiers de Kasserine'),
  ('ISAM Mahdia — Institut Supérieur des Arts et Métiers de Mahdia'),
  ('ISAM Manouba (La Mannouba) — Institut Supérieur des Arts du Multimédia de la Manouba'),
  ('ISAM Sfax — Institut Supérieur des Arts et Métiers de Sfax'),
  ('ISAM Sidi Bouzid — Institut Supérieur des Arts et Métiers de Sidi Bouzid'),
  ('ISAM Siliana — Institut Supérieur des Arts et Métiers de Siliana'),
  ('ISAM Tataouine — Institut Supérieur des Arts et Métiers de Tataouine'),
  ('ISB Béja — Institut Supérieur de Biotechnologie de Béja'),
  ('ISB Monastir — Institut Supérieur de Biotechnologie de Monastir'),
  ('ISB Sfax — Institut Supérieur de Biotechnologie de Sfax'),
  ('ISB Sidi Thabet (La Mannouba) — Institut Supérieur de Biotechnologie de Sidi Thabet'),
  ('ISBA Medenine (Médenine) — Institut Supérieur de Biologie Appliquée de Medenine'),
  ('ISBA Nabeul — Institut Supérieur des Beaux Arts de Nabeul'),
  ('ISBA Sousse — Institut Supérieur des Beaux Arts de Sousse'),
  ('ISBA Tunis — Institut Supérieur des Beaux Arts de Tunis'),
  ('ISCAE Manouba (La Mannouba) — Institut Supérieur de Comptabilité et d''Administration des Entreprises de Manouba'),
  ('ISCENF Carthage Dermech (Tunis) — Institut Supérieur des Cadres de l''Enfance Carthage Dermech'),
  ('ISCI Tunis — Institut Supérieur de la Civilisation Islamique de Tunis'),
  ('ISD Tunis (La Mannouba) — Institut Supérieur de Documentation de Tunis'),
  ('ISEAH Gafsa — Institut Supérieur des Etudes Appliquées en Humanités de Gafsa'),
  ('ISEAH Kef (Le Kef) — Institut Supérieur des Etudes Appliquées en Humanités du Kef'),
  ('ISEAH Mahdia — Institut Supérieur des Etudes Appliquées en Humanités de Mahdia'),
  ('ISEAH Tozeur — Institut Supérieur des Etudes Appliquées en Humanités de Tozeur'),
  ('ISEAH Tunis — Institut Supérieur des Etudes Appliquées en Humanité de Tunis'),
  ('ISÉAH Zaghouan — Institut Supérieur des Études Appliquées en Humanités de Zaghouan'),
  ('ISEASH Sbeïtla (Kasserine) — Institut Supérieur des Etudes Appliquées en Sciences Humaines de Sbeïtla'),
  ('ISEFC (Tunis) — Institut Supérieur de l''Education et de la Formation Continue'),
  ('ISEJ Gabès — Institut Supérieur des Etudes Juridiques de Gabès'),
  ('ISEJP Kairouan — Institut Supérieur des Etudes Juridiques et Politiques de Kairouan'),
  ('ISEPBG Soukra (Ariana) — Institut Supérieur des Etudes Préparatoires en Biologie et Géologie à Soukra'),
  ('ISES (La Mannouba) — Institut Supérieur de l’Education Spécialisée'),
  ('ISET Béja — Institut Supérieur des Etudes Technologiques de Béja'),
  ('ISET Bizerte — Institut Supérieur des Etudes Technologiques de Bizerte'),
  ('ISET Charguia (Ariana) — Institut Supérieur des Etudes Technologiques de Charguia'),
  ('ISET Gabès — Institut Supérieur des Etudes Technologiques de Gabès'),
  ('ISET Gafsa — Institut Supérieur des Etudes Technologiques de Gafsa'),
  ('ISET Jendouba — Institut Supérieur des Etudes Technologiques de Jendouba'),
  ('ISET Jerba (Médenine) — Institut Supérieur des Etudes Technologiques de Jerba'),
  ('ISET Kairouan — Institut Supérieur des Etudes Technologiques de Kairouan'),
  ('ISET Kasserine — Institut Supérieur des Etudes Technologiques de Kasserine'),
  ('ISET Kebili (Kébili) — Institut Supérieur des Etudes Technologiques de Kebili'),
  ('ISET Kef (Le Kef) — Institut Supérieur des Etudes Technologiques du Kef'),
  ('ISET Kélibia (Nabeul) — Institut Supérieur des Etudes Technologiques de Kélibia'),
  ('ISET Ksar Hellal (Monastir) — Institut Supérieur des Etudes Technologiques de Ksar Hellal'),
  ('ISET Mahdia — Institut Supérieur des Etudes Technologiques de Mahdia'),
  ('ISET Médenine — Institut Supérieur des Etudes Technologiques de Médenine'),
  ('ISET Nabeul — Institut Supérieur des Etudes Technologiques de Nabeul'),
  ('ISET Rades (Ben Arous) — Institut Supérieur des Etudes Technologiques de Rades'),
  ('ISET Sfax — Institut Supérieur des Etudes Technologiques de Sfax'),
  ('ISET Sidi Bouzid — Institut Supérieur des Etudes Technologiques de Sidi Bouzid'),
  ('ISET Sidi Dhrif (Tunis) — Institut Supérieur des Etudes Touristique de Sidi Dhrif'),
  ('ISET Siliana — Institut Supérieur des Etudes Technologiques de Siliana'),
  ('ISET Sousse — Institut Supérieur des Etudes Technologiques de Sousse'),
  ('ISET Tataouine — Institut Supérieur des Etudes Technologiques de Tataouine'),
  ('ISET Tozeur — Institut Supérieur des Etudes Technologiques de Tozeur'),
  ('ISET Zaghouan — Institut Supérieur des Etudes Technologiques de Zaghouan'),
  ('ISETCOM Tunis (Ariana) — Institut Supérieur des Etudes Technologiques en Communications de Tunis'),
  ('ISFF Sousse — Institut Supérieur de Finances et de Fiscalité de Sousse'),
  ('ISG Bizerte — Institut Supérieur de Gestion de Bizerte'),
  ('ISG Gabès — Institut Supérieur de Gestion de Gabès'),
  ('ISG Sousse — Institut Supérieur de Gestion de Sousse'),
  ('ISG Tunis — Institut Supérieur de Gestion de Tunis'),
  ('ISGI Sfax — Institut Supérieur de Gestion Industrielle de Sfax'),
  ('ISI (Ariana) — Institut Supérieur d''Informatique'),
  ('ISI Kef (Le Kef) — Institut Supérieur de l''Informatique du Kef'),
  ('ISI Mahdia — Institut Supérieur d''Informatique de Mahdia'),
  ('ISI Medenine (Médenine) — Institut Supérieur d''Informatique de Medenine'),
  ('ISIG Kairouan — Institut Supérieur d''Informatique et de Gestion de Kairouan'),
  ('ISIM Gabès — Institut Supérieur d''Informatique et de Multimédia de Gabès'),
  ('ISIM Monastir — Institut Supérieur d''Informatique et de Mathématiques de Monastir'),
  ('ISIM Sfax — Institut Supérieur d''Informatique et de Multimédia de Sfax'),
  ('ISITC Hammam Sousse (Sousse) — Institut Supérieur d''Informatique et des Technologies de Communication de Hammam Sousse'),
  ('ISL Gabès — Institut Supérieur des Langues de Gabès'),
  ('ISL Nabeul — Institut Supérieur des Langues de Nabeul'),
  ('ISL Tunis — Institut Supérieur des Langues de Tunis'),
  ('ISLA Moknine (Monastir) — Institut Supérieur des Langues Appliquées de Moknine'),
  ('ISLAI Béja — Institut Supérieur des Langues Appliquées et Informatique de Béja'),
  ('ISM Monastir — Institut Supérieur de la Mode de Monastir'),
  ('ISM Sfax — Institut Supérieur de Musique de Sfax'),
  ('ISM Sousse — Institut Supérieur de Musique de Sousse'),
  ('ISM Tunis — Institut Supérieur de Musique de Tunis'),
  ('ISMAI Kairouan — Institut Supérieur des Mathématiques Appliquées et de l''Informatique de Kairouan'),
  ('ISMP Tunis — Institut Supérieur des Métiers du Patrimoine de Tunis'),
  ('ISMT Kef (Le Kef) — Institut Supérieur de Musique et de Théâtre du Kef'),
  ('ISP Tabarka (Jendouba) — Institut Sylvo-Pastoral de Tabarka'),
  ('ISPA Bizerte — Institut Supérieur de Pêche et d''Aquaculture de Bizerte'),
  ('ISSAT Gabès — Institut Supérieur des Sciences Appliquées et de Technologie de Gabès'),
  ('ISSAT Gafsa — Institut Supérieur des Sciences Appliquées et de Technologie de Gafsa'),
  ('ISSAT Kairouan — Institut Supérieur des Sciences Appliquées et de Technologie de Kairouan'),
  ('ISSAT Kasserine — Institut Supérieur des Sciences Appliquées et de Technologie de Kasserine'),
  ('ISSAT Mahdia — Institut Supérieur des Sciences Appliquées et de Technologie de Mahdia'),
  ('ISSAT Mateur (Bizerte) — Institut Supérieur des Sciences Appliquées et de la Technologie de Mateur'),
  ('ISSAT Sousse — Institut Supérieur des Sciences Appliquées et de Technologie de Sousse'),
  ('ISSBA Tunis — Institut Supérieur des Sciences Biologiques Appliquées de Tunis'),
  ('ISSEP Gafsa — Institut Supérieur du Sport et de l''Education Physique de Gafsa'),
  ('ISSEP Kef (Le Kef) — Institut Supérieur du Sport et de l’Education Physique du Kef'),
  ('ISSEP Ksar Saïd (La Mannouba) — Institut Supérieur du Sport et de l''Education Physique de Ksar Saïd'),
  ('ISSEP Sfax — Institut Supérieur du Sport et de l''Education Physique de Sfax'),
  ('ISSH Jendouba — Institut Supérieur des Sciences Humaines de Jendouba'),
  ('ISSH Médenine — Institut Supérieur des Sciences Humaines de Médenine'),
  ('ISSH Tunis — Institut Supérieur des Sciences Humaines de Tunis'),
  ('ISSI Gabès — Institut Supérieur des Sciences Infirmières de Gabès'),
  ('ISSI Gabès — Institut Supérieur des Systèmes Industriels de Gabès'),
  ('ISSI Kairouan — Institut Supérieur des Sciences Islamiques de Kairouan'),
  ('ISSI Kef (Le Kef) — Institut Supérieur des Sciences Infirmières de Kef'),
  ('ISSI Sfax — Institut Supérieur des Sciences Infirmières de Sfax'),
  ('ISSI Sousse — Institut Supérieur des Sciences Infirmières de Sousse'),
  ('ISSI Tunis — Institut Supérieur des Sciences Infirmières de Tunis'),
  ('ISSTE Borj Cédria (Nabeul) — Institut Supérieur des Sciences et Technologies de l''Environnement de Borj Cédria'),
  ('ISSTE Gabès — Institut Supérieur des Sciences et Techniques des Eaux de Gabès'),
  ('ISSTE Gafsa — Institut Supérieur des Sciences et des Technologies de l''Energie de Gafsa'),
  ('IST Tunis — Institut Supérieur de Théologie de Tunis'),
  ('ISTEUB (Ariana) — Institut Supérieur des Technologies de l’Environnement de l''Urbanisme et du Bâtiment'),
  ('ISTIC (Nabeul) — Institut Supérieur des Technologies de l''Information et de la Communication'),
  ('ISTL Sousse — Institut Supérieur du Transport et de la Logistique de Sousse'),
  ('ISTM Tunis — Institut Supérieur des Technologies Médicales de Tunis'),
  ('SUP''COM Tunis (Ariana) — Ecole Supérieure des Communications de Tunis'),
  ('TBS (Ben Arous) — Tunis Business School'),
  ('UV (Tunis) — Université Virtuelle')
on conflict (name) do nothing;
